# Generated by Django 5.2.2 on 2025-06-18 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='max_dogs',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of dogs allowed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
