# Generated by Django 5.2.2 on 2025-06-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_payment_city_payment_country_payment_postcode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
