# Generated by Django 5.2.2 on 2025-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_dogs',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
